// Auto-generated slug word lists for Jetro slug generator
// Format: {WORDS_A[i]}{WORDS_B[j]}{2-char suffix}
// Example: frostypanda-k3
// Rules: all lowercase, 3–7 chars each, no duplicates, clean/fun/professional
// 1000 × 1000 = 1,000,000 base combinations × 36² suffix = ~1.3 billion unique slugs

export const WORDS_A: string[] = [
  // Blues & cool tones (3-7 chars)
  "icy", "aqua", "azure", "cobalt", "cyan", "inky", "navy", "steel", "teal",
  "cerule", "arctic", "glacial", "wintry",
  // Greens
  "fern", "jade", "leafy", "lush", "minty", "mossy", "olive", "pine", "sage",
  "virid", "verdant", "grassy", "herbal",
  // Warm tones
  "amber", "blush", "coral", "dusty", "ember", "fiery", "flame", "foxy",
  "ginger", "goldy", "ochre", "peach", "rosy", "ruddy", "rusty", "sandy",
  "sienna", "sunny", "tan", "tawny", "topaz", "warm",
  // Purples / pinks
  "lilac", "mauve", "misty", "plum", "ruby", "velvet", "violet",
  // Whites / lights / silvers
  "ashen", "bright", "chalky", "crisp", "fair", "frosty", "ivory", "lunar",
  "milky", "opal", "pearly", "shiny", "silky", "sleek", "snowy", "stark",
  // Darks
  "dark", "dusky", "ebony", "moody", "murky", "noir", "shadow", "smoky",
  "stony",
  // Weather / sky
  "balmy", "breezy", "chilly", "clear", "cloudy", "dewy", "foggy",
  "fresh", "gusty", "hazy", "humid", "rainy", "serene", "shady", "stormy",
  "tepid", "wild", "windy", "zephyr", "drizzly", "frosted",
  // Textures
  "bumpy", "cozy", "craggy", "crispy", "cushy", "fluffy", "foamy",
  "fuzzy", "glossy", "grainy", "gritty", "lumpy", "matte", "pebbly", "plush",
  "puffy", "rough", "satiny", "spongy", "suede", "wavy", "woolly",
  // Moods / feelings
  "blithe", "bold", "bouncy", "brave", "bubbly", "calm", "chipper",
  "curious", "dainty", "dandy", "dapper", "dear", "eager", "earnest",
  "easy", "elated", "fancy", "feisty", "fond", "free", "giddy", "glad",
  "gleeful", "glowing", "golden", "grand", "happy", "hearty", "hopeful",
  "jaunty", "jolly", "jovial", "joyful", "joyous", "keen", "kind",
  "lively", "lovable", "lucky", "mellow", "merry", "nimble", "noble",
  "peppy", "perky", "playful", "plucky", "polite", "proud", "pure",
  "quick", "quirky", "radiant", "rapid", "ready", "regal",
  "snappy", "social", "soft", "spry", "steady", "stellar",
  "sweet", "tender", "tidy", "trim", "trusty", "upbeat",
  "valiant", "vibrant", "vivid", "witty", "zany", "zealous", "zen",
  "zippy",
  // Nature / botanical feel (all ≤7 chars)
  "alpine", "birchy", "bloomy", "boggy", "boreal", "brambly", "briny",
  "bushy", "cedary", "clover", "coastal", "crispy", "crystal", "dappled",
  "earthy", "evening", "ferny", "flinty", "floral", "foresty",
  "gnarly", "gravel", "groovy", "hollow", "honeyed", "island", "jungly",
  "lavend", "loamy", "mango", "meadow",
  "mulchy", "nectar", "nomadic", "nordic", "oaken", "organic", "petal",
  "piney", "pollen", "pondy", "prairie", "primal", "reedy", "ripple",
  "river", "rocky", "rooted", "rustic", "saline", "shelly", "silvan",
  "sky", "slaty", "solar", "spicy", "spring", "sprout",
  "stream", "sunlit", "swampy", "sylvan", "tangy", "tidal", "timber",
  "torrid", "tropic", "tundra", "twilit", "upland", "valley", "vernal",
  "watery", "woody", "zonal",
  // Size / shape
  "beefy", "bony", "boxy", "brief", "broad", "bulky", "curvy", "deep",
  "dense", "elfin", "epic", "firm", "flat", "giant", "grand", "hollow",
  "huge", "lanky", "lean", "lithe", "lofty", "long", "mini",
  "narrow", "petite", "plump", "pointy", "puny", "round", "sharp",
  "short", "slim", "small", "solid", "squat", "steep", "stout", "svelte",
  "swift", "tall", "teeny", "thick", "thin", "tiny", "tonal", "wide",
  // Speed / energy
  "active", "agile", "alert", "brisk", "busy", "dashing", "dynamic",
  "fast", "fierce", "frantic", "hyper", "instant", "kinetic",
  "mighty", "potent", "rapid", "roaring", "rousing", "rushing", "soaring",
  "sonic", "speedy", "surging", "vital",
  // Light / glow (all ≤7 chars)
  "aurora", "blazing", "dim", "flashy", "gleamy", "glowing",
  "lit", "lucid", "neon", "pale", "shimmy", "sunlit",
  // Food-adjacent descriptors
  "buttery", "citrus", "creamy", "flaky", "fruity",
  "jammy", "juicy", "lemony", "malty", "nutty",
  "peachy", "salty", "savory", "sugary", "tart", "toasty", "zesty",
  // Misc pleasant descriptors (all ≤7 chars)
  "airy", "ample", "apt", "artful", "astute", "atomic", "avid",
  "bashful", "benign", "bonny", "brainy", "brash", "candid",
  "capable", "caring", "catchy", "certain", "cheeky", "cheery", "chic",
  "choice", "civic", "classic", "clever", "close", "comfy", "compact",
  "cordial", "cosmic", "crafty", "cunning", "cute", "deft", "devout",
  "divine", "doting", "dreamy", "driven", "electric", "elegant",
  "faithful", "famous", "fleet", "focused", "formal", "frank",
  "frugal", "full", "funny", "gallant", "gentle", "gifted", "giving",
  "gracious", "guided", "handy", "honest", "ideal", "idyllic", "inspired",
  "knowing", "loyal", "majestic", "mindful", "modest",
  "natural", "neat", "nice", "optimal", "orderly", "original",
  "patient", "peaceful", "poetic", "polished", "precise", "present",
  "prime", "pristine", "prolific", "quaint", "quiet",
  "rational", "refined", "rested", "rich", "robust", "safe",
  "savvy", "shrewd", "sincere", "skilled", "smart", "snug",
  "sober", "sociable", "spirited", "stable", "staunch", "stoic",
  "strong", "sturdy", "subtle", "super", "supreme",
  "tactful", "talented", "thorough", "tranquil", "trusting", "truthful",
  "tuned", "unique", "united", "urbane", "useful", "vast", "versed",
  "vigorous", "wary", "whole", "wily", "wise", "worthy", "xenial",
  // Extended set A — to reach 1000
  "ablaze", "abrupt", "ace", "adept", "adorable", "adroit",
  "affable", "ageless", "airy", "aloft",
  "ambient", "amused", "angelic", "animated", "ardent", "aromatic",
  "artisan", "ascend", "assured", "astral", "attuned",
  "august", "aural", "balanced", "beatific", "benevolent",
  "bespoke", "blessed", "blissful", "bountiful", "brazen",
  "buoyant", "capable", "cardinal", "casual", "catlike", "centered",
  "champion", "chirpy", "chroma", "citrine", "civil", "clement",
  "climbing", "colorful", "comely", "composed", "concord",
  "constant", "content", "correct", "courtly", "crafted",
  "cultured", "cutting", "darting", "dauntless", "decisive",
  "dedicated", "delicate", "devoted", "docile", "dominant", "durable",
  "effulgent", "elastic", "emerald", "eminent", "enduring",
  "engaging", "equable", "euphoric", "exalted", "exuberant", "fabled",
  "falcon", "fearless", "festive", "flawless", "flowing", "forthright",
  "forward", "fragrant", "fruiting", "gemlike", "genial", "genteel",
  "genuine", "glory", "graceful", "grateful", "grounded",
  "growing", "hallowed", "heartfelt", "heroic", "holistic",
  "homeward", "horizon", "humble", "hushed", "illumined",
  "impartial", "inclined", "informed", "integral", "intense",
  "inward", "jubilant", "keystone", "kindly", "kinship",
  "lambent", "laudable", "lavish", "leading", "legible", "liberated",
  "light", "likeable", "limber", "linear", "longing",
  "manifold", "mature", "measured", "memorable", "merciful",
  "musical", "newfound", "nourished", "nurturing", "observant",
  "open", "outgoing", "perceptive", "perfect", "persevering",
  "pivotal", "placid", "poised", "positive", "prepared",
  "principled", "prudent", "reaching", "receptive", "reflective",
  "resilient", "resolute", "resourceful", "respected", "restful",
  "righteous", "seasoned", "sensible", "settled", "shining",
  "singularly", "soulful", "sowing", "spacious", "splendid",
  "steadfast", "sterling", "sure", "tactful", "thankful",
  "thoughtful", "thriving", "timeless", "together", "transparent",
  "treasured", "triumphant", "trustworthy", "unbounded", "undaunted",
  "unified", "upward", "valued", "venerable", "versatile",
  "vigilant", "vocal", "welcoming", "wholesome", "winsome", "wondrous",
  "aeolian", "altaic", "analog", "anew", "aplenty",
  "aquifer", "ardor", "aroma", "banner", "baronial",
  "beckon", "bestow", "brazen", "bridging", "brilliant",
  "candent", "celestial", "chirping", "circling", "clarion",
  "cleanly", "clement", "clover", "collected",
  "confident", "conscious", "correct", "courageous",
  "daydream", "devoted", "discerning", "distinct",
  "earnest", "enduring", "fidelity", "fitting",
  "favorable", "fragrant", "fulfilled", "gemstone",
  "guidance", "guiding", "harmonious", "heartfelt",
  "heroic", "humble", "illumined", "immense",
  "improved", "inclusive", "innovative", "insightful",
  "inventive", "iridescent", "jubilant", "keenly",
  "laudable", "leading", "luminant", "mindful",
  "momentous", "motivated", "mystical", "natural",
  "nourished", "nurturing", "olympian", "optimum",
  "perceptive", "placid", "plentiful", "positive",
  "prudent", "reaching", "receptive", "reflective",
  "refreshed", "resilient", "resolute", "rich",
  "righteous", "seasoned", "sensible", "serene",
  "shining", "soulful", "spacious", "splendid",
  "steadfast", "sterling", "sublime", "thriving",
  "timeless", "tranquil", "treasured", "unified",
  "upward", "valued", "venerable", "versatile",
  "vibrant", "vigilant", "wondrous", "zealous",
];

export const WORDS_B: string[] = [
  // Mammals
  "ape", "bear", "bison", "boar", "bull", "camel", "cat", "colt", "deer",
  "dog", "dolphin", "elk", "ferret", "fox", "fawn", "gerbil", "goat",
  "hamster", "hare", "horse", "ibex", "jackal", "jaguar", "koala",
  "lemur", "lion", "llama", "lynx", "mink", "mole", "moose", "mouse",
  "mule", "okapi", "otter", "panda", "panther", "pig", "pony",
  "rabbit", "raccoon", "ram", "rat", "sable", "seal",
  "sheep", "shrew", "skunk", "sloth", "stoat", "tapir", "tiger", "vole",
  "weasel", "wolf", "yak", "zebra", "bison", "dingo", "gecko", "hyena",
  "impala", "kinkajou", "margay", "marten", "meerkat", "narwhal",
  "ocelot", "quokka", "serval", "tayra", "uakari", "vicuna",
  // Birds
  "crane", "crow", "dove", "duck", "eagle", "egret", "finch",
  "goose", "hawk", "heron", "ibis", "jay", "kite", "lark", "macaw",
  "martin", "merlin", "oriole", "osprey", "owl", "parrot",
  "pelican", "petrel", "pigeon", "plover", "quail", "raven", "robin",
  "rook", "sparrow", "stork", "swallow", "swan", "swift",
  "tern", "thrush", "toucan", "vulture", "warbler", "wren", "avocet",
  "bittern", "bulbul", "buzzard", "chukar", "curlew", "dipper",
  "dunlin", "gannet", "godwit", "grouse", "hoopoe", "junco", "kestrel",
  "linnet", "magpie", "myna", "ovenbird", "pewee", "phoebe",
  "pipit", "plover", "redstart", "sandpiper", "shrike",
  "skimmer", "skylark", "snipe", "tattler", "teal", "treecreeper",
  "turnstone", "vireo", "wagtail", "wheatear", "willet", "woodcock",
  // Aquatic / reptile
  "bream", "carp", "clam", "cod", "crab", "dace", "eel", "frog",
  "guppy", "iguana", "koi", "lobster", "mollusc", "mussel",
  "newt", "octopus", "oyster", "perch", "prawn", "roach", "salmon",
  "scallop", "shrimp", "skate", "snail", "squid",
  "toad", "trout", "tuna", "turtle", "urchin", "walrus", "whelk",
  "barbel", "blenny", "bonefish", "burbot", "catfish", "chub",
  "darter", "dogfish", "dory", "flounder", "garfish", "gudgeon",
  "halibut", "herring", "lamprey", "loach", "lungfish", "minnow",
  "mudskipper", "mullet", "paddlefish", "pikeperch", "pipefish",
  "plaice", "ruffe", "sculpin", "stickleback", "sunfish",
  "tench", "tilapia", "turbot", "vendace", "whiting", "zander",
  // Insects / bugs
  "ant", "bee", "beetle", "bug", "cicada", "cricket", "firefly",
  "gnat", "ladybug", "locust", "mantis", "moth", "wasp", "aphid",
  "borer", "damselfly", "earwig", "flea", "hornet", "mayfly",
  "midge", "sawfly", "springtail", "stonefly", "termite", "thrip",
  "weevil",
  // Plants / botanicals (all ≤7 chars)
  "acorn", "agave", "aloe", "arum", "aspen", "aster", "balsa", "bamboo",
  "bay", "birch", "bloom", "bonsai", "briar",
  "bud", "cactus", "calyx", "catnip", "cedar", "clover",
  "cone", "cosmos", "creeper", "cypress", "dahlia", "daisy",
  "dill", "dock", "elder", "elm", "fennel", "fern", "fig", "fir",
  "flax", "flora", "flower", "frond", "gorse", "grain", "grass",
  "grove", "hazel", "heath", "herb", "holly", "hop", "iris",
  "ivy", "jasmine", "juniper", "laurel",
  "leaf", "lichen", "lilac", "lily", "linden", "lotus", "lupine",
  "mallow", "maple", "mint", "moss", "mulch", "myrtle", "nettle",
  "oak", "orchid", "osier", "pansy", "parsley", "peony", "petal",
  "pine", "poplar", "poppy", "reed", "root", "rose", "rush",
  "rye", "sedge", "seed", "sorrel", "spore", "spruce", "stem",
  "straw", "sumac", "thistle", "thyme", "thorn", "tilia", "tulip",
  "turf", "vervain", "vine", "violet", "willow", "yarrow", "yew",
  "zinnia", "ageratum", "aralia", "aronia", "banksia",
  "boronia", "bougain", "bromeliad", "buddleia", "calibrachoa",
  "callistemon", "camellia", "candytuft", "carnation",
  "catmint", "celosia", "chervil", "chicory", "columbine",
  "cornflower", "cotoneaster",
  "cowslip", "cyclamen",
  "delphinium", "deutzia",
  "diascia", "digitalis", "echinacea",
  "echium", "euonymus", "euphorbia", "fatsia",
  "forsythia", "freesia", "fritillary", "fuchsia", "gaillardia",
  "gazania", "gentian",
  "gladiola", "gypsophila",
  "helenium", "helianthus", "helichrysum",
  "hemerocallis", "heuchera",
  "hibiscus", "hosta", "hyacinth",
  "hydrangea", "inula",
  "kniphofia", "lavatera",
  "leucojum", "lewisia",
  "liatris", "linaria", "lobelia",
  "loosestrife", "lunaria",
  "magnolia", "mandevilla",
  "mimosa", "muscari", "narcissus",
  "nemesia", "nepeta", "nicotiana",
  "nigella", "osteospermum",
  "oxalis", "penstemon", "petunia",
  "phlox", "physalis",
  "pieris", "pittosporum", "platycodon",
  "plumbago", "polemonium",
  "potentilla", "primrose",
  "pulmonaria", "ranunculus",
  "romneya", "rudbeckia",
  "salpiglossis", "salvia",
  "scabiosa", "schizanthus",
  "sedum", "senecio", "sidalcea",
  "sisyrinchium", "solanum",
  "solidago", "spiraea",
  "stachys", "statice", "stock",
  "tagetes", "tansy", "tiarella",
  "torenia", "trachymene",
  "tradescantia", "tropaeolum",
  "tweedia", "ursinia",
  "verbena", "veronica",
  "viburnum", "weigela",
  "xeranthemum", "xylosma",
  // Food & drink (all ≤7 chars)
  "acai", "almond", "anise", "apple", "apricot", "avocado", "bagel",
  "barley", "bean", "berry", "biscuit", "bread",
  "brie", "broth", "brownie", "bun", "butter", "candy", "caramel",
  "cashew", "chai", "cherry", "chive", "choco", "cider", "citron",
  "clove", "cobbler", "cocoa", "coconut", "coffee",
  "cookie", "cream", "crumpet", "cumin", "currant", "custard",
  "dates", "donut", "fudge",
  "gelato", "ginger", "grape", "granola", "guava", "halvah",
  "honey", "jam", "kiwi", "latte", "lemon",
  "lime", "lychee", "macaron", "mango", "melon", "mochi",
  "mocha", "muffin", "nectar", "noodle", "nutmeg", "oat", "olive",
  "orange", "papaya", "peanut", "pear", "pecan", "pepper", "pesto",
  "pickle", "pie", "plum", "pomelo", "pretzel", "quinoa",
  "raisin", "scone", "sesame", "sorbet", "soy", "spelt",
  "sugar", "syrup", "tahini", "tart", "tea",
  "toffee", "truffle", "vanilla", "waffle",
  "wheat", "yuzu", "zest",
  // Gems / minerals (all ≤7 chars)
  "agate", "amber", "beryl", "chert", "citrine",
  "crystal", "diamond", "emerald", "flint",
  "garnet", "geode", "granite", "jasper", "jet", "lapis",
  "marble", "mica", "onyx", "opal", "pearl",
  "pyrite", "quartz", "ruby", "shale", "slate", "spinel",
  "topaz",
  // Places / landscape (all ≤7 chars)
  "alcove", "arch", "atoll", "basin", "beach", "bluff",
  "bog", "brook", "butte", "canyon", "cape", "cave", "channel",
  "cliff", "coast", "cove", "creek", "crest", "delta", "den", "dune",
  "fjord", "glade", "glen", "gorge", "grotto", "grove",
  "gulf", "harbor", "haven", "heath", "hill", "hollow", "inlet",
  "island", "islet", "jungle", "knoll", "lagoon", "lake", "ledge",
  "marsh", "mire", "moor", "mount", "oasis", "ocean",
  "pasture", "peak", "plain", "plateau", "pond",
  "pool", "prairie", "rapids", "ravine", "reef", "ridge", "rift",
  "river", "rock", "shore", "slope", "spring", "steppe", "summit",
  "swamp", "tor", "trail", "tundra", "vale", "valley", "vent",
  "wood",
  // Objects / things (all ≤7 chars)
  "anchor", "anvil", "arc", "arrow", "axle", "badge", "barrel", "bead",
  "beam", "bell", "blade", "bolt", "bottle", "bowl", "box", "brace",
  "bridge", "brooch", "bucket", "candle", "capsule", "cart",
  "charm", "chisel", "clasp", "coil", "coin", "compass", "cord",
  "crown", "cube", "cup", "dial", "drum", "flame", "flask", "flute",
  "fork", "frame", "gem", "globe", "grid", "hammer", "harp", "helm",
  "hook", "horn", "jar", "key", "knot", "lamp", "lantern",
  "latch", "lathe", "lens", "loom", "lute", "mast", "medal", "mirror",
  "moon", "needle", "nest", "node", "orb", "paddle", "pail", "palette",
  "peg", "pendant", "pin", "pipe", "plank", "plate", "plume", "pod",
  "post", "prism", "pulley", "quill", "rack", "relay", "ring", "rod",
  "rope", "rudder", "sail", "scroll", "shard", "shell", "shield",
  "sieve", "signal", "slab", "slide", "spool", "spoke",
  "staff", "stamp", "star", "stave", "stone", "strand",
  "strap", "string", "strut", "stylus", "tablet", "tile",
  "token", "torch", "tower", "truss", "tube", "twine", "urn",
  "valve", "vessel", "vial", "wedge", "wheel", "wick", "wing",
  "wire", "yoke",
  // Celestial / cosmic (≤7 chars)
  "comet", "corona", "cosmos", "eclipse", "flare", "galaxy",
  "halo", "meteor", "moon", "nebula", "nova", "orbit", "photon",
  "planet", "pulsar", "quasar", "solstice", "sunspot",
  "transit", "zenith",
  // Structures / architecture (≤7 chars)
  "abbey", "aisle", "altar", "arcade", "atrium", "barn",
  "bastion", "bower", "cabin", "castle", "citadel",
  "court", "dome", "eave", "fort", "foyer", "gable", "gallery",
  "gate", "gazebo", "hall", "hearth", "inn", "keep", "lodge", "manor",
  "mill", "moat", "pagoda", "parapet", "pier", "portico",
  "ruin", "sanctum", "spire", "stable", "terrace", "tower", "vault",
  "veranda", "windmill",
  // Abstract nouns / concepts (pleasant, ≤7 chars)
  "apex", "aura", "bloom", "boon", "calm", "core", "crest",
  "dawn", "dream", "dusk", "echo", "epoch", "essence", "ethos", "flow",
  "flux", "form", "glow", "grace", "gust", "hush", "light", "link",
  "lore", "lull", "nexus", "norm", "note", "path", "peace",
  "pulse", "quest", "realm", "rise", "root", "scope", "seed",
  "shift", "skill", "spark", "spirit", "spur", "surge",
  "sync", "tide", "trace", "trail", "trek", "trend", "unity",
  "valor", "verve", "vigor", "virtue", "vista", "wave",
  "will", "wind", "wisdom", "wish", "wonder", "zeal",
];
